// <auto-generated />
namespace DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class expire_In_TradeMark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(expire_In_TradeMark));
        
        string IMigrationMetadata.Id
        {
            get { return "202001280916026_expire_In_TradeMark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
